// <auto-generated />
using DataAccessLayer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(BallzContext))]
    [Migration("20231219121311_ChangeNumericCapacity")]
    partial class ChangeNumericCapacity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.ChristmasBall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("color");

                    b.Property<string>("Effects")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("varchar(2)")
                        .HasColumnName("effects");

                    b.Property<decimal>("Radius")
                        .HasColumnType("numeric(4, 2)")
                        .HasColumnName("radius");

                    b.Property<decimal>("X")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("x");

                    b.Property<decimal>("Y")
                        .HasColumnType("numeric(5, 2)")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("PK__Christma__3214EC07A11BBCE2");

                    b.ToTable("ChristmasBalls");
                });
#pragma warning restore 612, 618
        }
    }
}
