CREATE DATABASE BALLZ

GO
USE BALLZ

CREATE TABLE ChristmasBalls(
Id INT IDENTITY(1, 1) PRIMARY KEY,
x NUMERIC(5,2) NOT NULL,
y NUMERIC(5,2) NOT NULL,
radius NUMERIC(5,2) NOT NULL,
color VARCHAR(10) NOT NULL,
effects VARCHAR(2) NOT NULL)